version: '3.8'

services:
  ffc-sfi-payments:
    build:
      context: .
      target: production
    image: ffc-sfi-payments
    depends_on:
      - ffc-sfi-payments-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-payments-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      PROCESSING_TOPIC_ADDRESS: ${PROCESSING_TOPIC_ADDRESS:-notset}
      PROCESSING_SUBSCRIPTION_ADDRESS: ${PROCESSING_SUBSCRIPTION_ADDRESS:-notset}
      ACKNOWLEDGEMENT_TOPIC_ADDRESS: ${ACKNOWLEDGEMENT_TOPIC_ADDRESS:-notset}
      ACKNOWLEDGEMENT_SUBSCRIPTION_ADDRESS: ${ACKNOWLEDGEMENT_SUBSCRIPTION_ADDRESS:-notset}
      RETURN_TOPIC_ADDRESS: ${RETURN_TOPIC_ADDRESS:-notset}
      RETURN_SUBSCRIPTION_ADDRESS: ${RETURN_SUBSCRIPTION_ADDRESS:-notset}
      PAYMENTSUBMIT_TOPIC_ADDRESS: ${PAYMENTSUBMIT_TOPIC_ADDRESS:-notset}
      POSTGRES_DB: ffc_sfi_payments
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-sfi-payments-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
  
  ffc-sfi-payments-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_sfi_payments
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
