version: '3.8'

services:
  ffc-pay-processing:
    build:
      context: .
      target: production
    image: ffc-pay-processing
    depends_on:
      - ffc-pay-processing-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-processing-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      PROCESSING_TOPIC_ADDRESS: ${PROCESSING_TOPIC_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      PROCESSING_SUBSCRIPTION_ADDRESS: ${PROCESSING_SUBSCRIPTION_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      ACKNOWLEDGEMENT_TOPIC_ADDRESS: ${ACKNOWLEDGEMENT_TOPIC_ADDRESS:-ffc-pay-acknowledge}${MESSAGE_QUEUE_SUFFIX}
      ACKNOWLEDGEMENT_SUBSCRIPTION_ADDRESS: ${ACKNOWLEDGEMENT_SUBSCRIPTION_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      RETURN_TOPIC_ADDRESS: ${RETURN_TOPIC_ADDRESS:-ffc-pay-return}${MESSAGE_QUEUE_SUFFIX}
      RETURN_SUBSCRIPTION_ADDRESS: ${RETURN_SUBSCRIPTION_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      PAYMENTSUBMIT_TOPIC_ADDRESS: ${PAYMENTSUBMIT_TOPIC_ADDRESS:-ffc-pay-submit}${MESSAGE_QUEUE_SUFFIX}
      DEBT_TOPIC_ADDRESS: ${DEBT_TOPIC_ADDRESS:-ffc-pay-debt-data}${MESSAGE_QUEUE_SUFFIX}
      QC_TOPIC_ADDRESS: ${QC_TOPIC_ADDRESS:-ffc-pay-debt-data-response}${MESSAGE_QUEUE_SUFFIX}
      QC_SUBSCRIPTION_ADDRESS: ${QC_SUBSCRIPTION_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      MANUALCHECK_TOPIC_ADDRESS: ${MANUALCHECK_TOPIC_ADDRESS:-ffc-pay-manual-check-data}${MESSAGE_QUEUE_SUFFIX}
      QCMANUALCHECK_TOPIC_ADDRESS: ${MANUALCHECK_TOPIC_ADDRESS:-ffc-pay-quality-check}${MESSAGE_QUEUE_SUFFIX}
      QCMANUALCHECK_SUBSCRIPTION_ADDRESS: ${MANUALCHECK_SUBSCRIPTION_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      EVENT_TOPIC_ADDRESS: ${EVENT_TOPIC_ADDRESS:-ffc-pay-event}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc_pay_processing
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-pay-processing-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      USE_MANUAL_LEDGER_CHECK: "true"
  
  ffc-pay-processing-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_pay_processing
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
