version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-payments:
    build:
      target: development
    image: ffc-sfi-payments-development
    ports:
      - "3008:3008"
      - "9233:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    command: >
      sh -c "
        scripts/wait-for kafka:9093 --
        npm run start:watch"
    depends_on:
      - kafka

  ffc-sfi-payments-postgres:
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    ports:
      - "9095:9094"

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - 9001:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka

volumes:
  postgres_data: {}
