version: '3.8'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-pay-processing:
    build:
      target: development
    image: ffc-pay-processing-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    depends_on:
      - kafka

  ffc-pay-processing-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
