version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-payments:
    build:
      target: development
    image: ffc-sfi-payments-development
    container_name: ffc-sfi-payments-development
    ports:
      - "9233:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json

  ffc-sfi-payments-postgres:
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
