{{- include "ffc-helm-library.container-secret" (list . "ffc-pay-processing.container-secret") -}}
{{- define "ffc-pay-processing.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
{{- end -}}
