{{- include "ffc-helm-library.container-config-map" (list . "ffc-sfi-payments.config-map") -}}
{{- define "ffc-sfi-payments.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  PROCESSING_TOPIC_ADDRESS: {{ quote .Values.container.processingTopicAddress }}
  PROCESSING_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.processingSubscriptionAddress }}
  ACKNOWLEDGEMENT_TOPIC_ADDRESS: {{ quote .Values.container.acknowledgementTopicAddress }}
  ACKNOWLEDGEMENT_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.acknowledgementSubscriptionAddress }}
  RETURN_TOPIC_ADDRESS: {{ quote .Values.container.returnTopicAddress }}
  RETURN_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.returnSubscriptionAddress }}
  PAYMENTSUBMIT_TOPIC_ADDRESS: {{ quote .Values.container.paymentSubmitTopicAddress }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
{{- end -}}
