environment: development
name: ffc-sfi-payments
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-payments

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-sfi-payments-config-map

containerSecret:
  name: ffc-sfi-payments-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReplicas: 2
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 180Mi
  requestCpu: 40m
  limitMemory: 280Mi
  limitCpu: 300m
  port: 3008
  messageQueueHost: namespace.servicebus.windows.net
  processingTopicAddress: ffc-sfi-payment-processing
  processingSubscriptionAddress: ffc-sfi-payment-processing-payments
  acknowledgementTopicAddress: ffc-sfi-payment-acknowledgement
  acknowledgementSubscriptionAddress: ffc-sfi-payment-acknowledgement-payments
  returnTopicAddress: ffc-sfi-payment-return
  returnSubscriptionAddress: ffc-sfi-payment-return-payments
  paymentSubmitTopicAddress: ffc-sfi-payment-submit

postgresService:
  postgresDb: ffc_sfi_payments
  # postgresExternalName is the external host name to which PostgreSQL
  # requests should be forwarded. If empty, PostgreSQL is assumed to be
  # within the cluster and accessible via postgresHost
  postgresExternalName:
  postgresHost: ffc-sfi-payments-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

readinessProbe:
  path: /healthy
  port: 3008
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3008
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
